name: rapture_tool
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '^3.2.0'

dependencies:
  bw_utils:
    git: https://github.com/Brazilian-Warriors/dart_bw_utils.git
  charset: ^2.0.1
  #   path: '../dart_bw_utils' 
#  path: ^1.7.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.21.0
